function _ensure_bigint_generators(rays::AbstractMatrix{<:Integer})
    return Matrix{BigInt}(rays)
end

function _ensure_bigint_generators(rays::AbstractMatrix{<:Integer}, config::OracleConfig)
    return Matrix{BigInt}(rays)
end

function _ensure_bigint_generators(rays::AbstractMatrix{<:Real}, config::OracleConfig)
    nrows, ncols = size(rays)
    out = Matrix{BigInt}(undef, nrows, ncols)
    for i in 1:nrows
        out[i, :] = rationalize_ray_coordwise(view(rays, i, :), config)
    end
    return out
end

"""
    enumerate_facets(rays, config=OracleConfig(); backend=NormalizCLIBackend()) -> Matrix{BigInt}

Given a matrix of extreme rays (rows), compute the support hyperplanes (facet normals) of the
cone they generate. Rays are rationalized to exact integers before passing to Normaliz.

Returns a `Matrix{BigInt}` whose rows are facet normals. Errors if the cone has lineality
(is not pointed).

See also: [`validate_facet`](@ref), [`compute_cone`](@ref).
"""
function enumerate_facets(
    rays::AbstractMatrix{<:Real},
    config::OracleConfig=OracleConfig();
    backend::AbstractNormalizBackend=NormalizCLIBackend(),
)
    G = _ensure_bigint_generators(rays, config)
    result = compute_cone(backend, G, config)
    is_pointed(result) || error(
        "enumerate_facets: cone has lineality space of dimension $(size(result.lineality_space, 1)); only pointed cones are supported"
    )
    return result.support_hyperplanes
end

"""
    validate_facet(normal, rays, config=OracleConfig()) -> Bool

Check that `normal` is a valid facet of the cone generated by `rays`: verifies
`h ⋅ r ≥ 0` for every row `r` of `rays`. Accepts both integer and floating-point inputs
(floating-point inputs are rationalized first).

See also: [`enumerate_facets`](@ref).
"""
function validate_facet(
    normal::AbstractVector{<:Integer},
    rays::AbstractMatrix{<:Integer},
    config::OracleConfig=OracleConfig(),
)
    h = Vector{BigInt}(normal)
    G = _ensure_bigint_generators(rays)
    for i in 1:size(G, 1)
        if dot(h, view(G, i, :)) < 0
            return false
        end
    end
    return true
end

function validate_facet(
    normal::AbstractVector{<:Real},
    rays::AbstractMatrix{<:Real},
    config::OracleConfig=OracleConfig(),
)
    h = rationalize_ray_coordwise(normal, config)
    G = _ensure_bigint_generators(rays, config)
    return validate_facet(h, G, config)
end
